# This rule is not used by the project helms itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to tpl.vipex.cc resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helms
    app.kubernetes.io/managed-by: kustomize
  name: dptools-viewer-role
rules:
- apiGroups:
  - tpl.vipex.cc
  resources:
  - dptools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tpl.vipex.cc
  resources:
  - dptools/status
  verbs:
  - get
