# This rule is not used by the project helms itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over tpl.vipex.cc.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helms
    app.kubernetes.io/managed-by: kustomize
  name: dptools-admin-role
rules:
- apiGroups:
  - tpl.vipex.cc
  resources:
  - dptools
  verbs:
  - '*'
- apiGroups:
  - tpl.vipex.cc
  resources:
  - dptools/status
  verbs:
  - get
